//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.UnitTest.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Sapphire : DbContext
    {
        public Sapphire()
            : base("name=Sapphire")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<sys_Config> sys_Config { get; set; }
        public virtual DbSet<sys_UserAuth_Function> sys_UserAuth_Function { get; set; }
    
        public virtual ObjectResult<GetLinkDisconectInfo_Result> GetLinkDisconectInfo(string userId, Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("beginTime", beginTime) :
                new ObjectParameter("beginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLinkDisconectInfo_Result>("GetLinkDisconectInfo", userIdParameter, beginTimeParameter, endTimeParameter);
        }
    }
}
