//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.UnitTest.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Config
    {
        public string Key { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsConfigurable { get; set; }
        public string FromModule { get; set; }
    }
}
