//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.UnitTest.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_UserAuth_Function
    {
        public string UserId { get; set; }
        public string TopMonitorXml { get; set; }
        public string TopManageXml { get; set; }
    }
}
